### ISSUE TITLE
Word Segmentation Support? 

### ISSUE THREAD

**Issue by sgon00** [pgroonga/pgroonga#102]
Hi, first, thank you very much for this extension. I am using it for LIKE operations (with `&@~` and `&@` operators). It's pretty fast. 

I am a newbie on postgresql and full text search (FTS) technique. So what I am about to say can be wrong.

**I have no doubt that I will use `pgroonga` for LIKE operations. But I am not sure if it will be faster for FTS than those extensions which support Word Segmentation.**

*(Btw, does pgroonga support Word Segmentation? I don't find any docs about it.)*

I am from China and I find out there are two FTS extensions for Chinese: https://github.com/jaiminpan/pg_jieba and https://github.com/amutu/zhparser.

With the above two FTS extensions, '保障房的资金压力' will break into  '保障' & '房' & '资金' & '压力'.
 '的' will be ignored during search because it's a stop word.

Some psql console tests:

```sql
testdb1=> SELECT to_tsquery('jiebaqry', '保障房的资金压力');
           to_tsquery
---------------------------------
 '保障' & '房' & '资金' & '压力'

testdb1=> select where to_tsvector('jiebaqry','保障房的资金压力') @@ to_tsquery('jiebaqry','的');
NOTICE:  text-search query contains only stop words or doesn't contain lexemes, ignored
--
(0 rows)
```

From the above psql console outputs, you can see that `的` will be simply ignored. But with pgroonga, it will search for '的' too because it doesn't deal with word segmentation and stop word. 

Again, I am a newbie and all the above words can be wrong. And I haven't done any performance tests yet (not sure how to do it properly). So I am not sure which is faster on FTS, pgroonga or (zhparser or pg_jieba). 

*(Btw zhparser and pg_jieba don't support LIKE operations)*

Can anyone give me any tips or suggestions on this topic, please? 

Thank you very much.

**Comment by kenhys** [comment]
Do you just mention about difference of PGroonga behavior in word segmentation for Chinese as an example?
Or word segmentation functionality is really required in performance tests?

In generally speaking, PGroonga uses bigram as a tokenizer(by default, it can be customized), so, it doesn't care word segmentation and stop word because it depends context.(In other words, it requires a tokenizer for language specific. For Japanese, it has TokenMecab http://groonga.org/docs/reference/tokenizers/token_mecab.html, For Chinese, it has TokenFriso, https://github.com/kenhys/groonga-tokenizer-friso but it doesn't work anymore with recent version )

In point view of performance test, we know the specific benchmark result(PGroonga vs textsearch vs pg_trgm).
Here is the one:
 https://pgroonga.github.io/reference/pgroonga-versus-textsearch-and-pg-trgm.html
It may be differ when benchmark data is changed, but the trend will be same I guess.

**Comment by sgon00** [comment]
@kenhys Thanks a lot for the reply. I mean both. But my main concern is **if I should use pgroonga for Chinese FTS or not**. I hope there is a performance comparison between pgroonga versus (pg_jieba or zhparser). Btw, Stop word should be important. `的` in Chinese doesn't mean anything in any context and should be ignored in all cases for search. It's just similar to `the` in English. (well, not the same at all, but similar functionality. `the` doesn't mean anything and should not be searched).

**Comment by sgon00** [comment]
I am closing this issue. @kenhys has confirmed that pgroonga does not support word segmentation for Chinese. I also did a simple performance testing on FTS. 

* For full text search, pgroonga is more accurate, but a little bit slower than pg_jieba, because it doesn't segment words. Thus for full text searching from a long text column (eg: body text of many articles), I will use pg_jieba for now.

* For LIKE, as what I said before, I will use pgroonga for LIKE operation. Because pg_jieba does not support LIKE operation. For example, when searching from short text column (eg: title of many articles) and I am more care of accuracy, I will use pgroonga `&@~` which is much more accurate than `to_tsvector() @@ to_tsquery()`. 

I am not sure what I found is correct or not. That is my result so far. Closing it.

**Comment by kenhys** [comment]
@sgon00 

This issue is closed already, I'll put some hint for the record. I hope it will  help someone.

It is not related to stop word functionality directly, as a another idea, it may be helpful to use `scorer_tf_idf` from PGroonga.
If you use `scorer_tf_idf`, the score of more important term gets larger than others.(maybe)
(It may be able to do a similar thing as stop word by handling score correctly)

Here is the documentation about `scorer_tf_idf`.

http://groonga.org/docs/reference/scorers/scorer_tf_idf.html


Here is the sample schema and data:

```
CREATE TABLE memos (
          id integer,
          content text
);

INSERT INTO memos (content) VALUES ('这是我的书 我的书 我的幸福');
INSERT INTO memos (content) VALUES ('幸福的家庭');
INSERT INTO memos (content) VALUES ('我的手机忘带了');

CREATE INDEX memos_index
          ON memos
       USING pgroonga (content pgroonga_text_full_text_search_ops_v2);                                                                     
```

Then search `的` with `scorer_tf_idf(content)`:

```
SELECT pgroonga_command('select',
       ARRAY['table', pgroonga_table_name('memos_index'),
       'match_columns', 'scorer_tf_idf(content)',
       'query', 'content:~"的"',
       'output_columns', 'content, _score',
       'sort_keys', '-_score'
       ]);
```

The above syntax is derived from Groonga ( http://groonga.org/ ), so you may not familiar with it.
`'query', 'content:~"的"'` is equivalent to `content &@~ 的`.

It returns the following result.

```
[[0,1561535645.599753,0.000141143798828125],[[[3],[["content","LongText"],["_score","Int32"]],["这是我的书 我的书 我的幸福",2],["我的手机忘
带了",1],["幸福的家庭",1]]]]
```

Then search `书` with `scorer_tf_idf(content)`:

```
SELECT pgroonga_command('select',
       ARRAY['table', pgroonga_table_name('memos_index'),
       'match_columns', 'scorer_tf_idf(content)',
       'query', 'content:~"书"',
       'output_columns', 'content, _score',
       'sort_keys', '-_score'
       ]);
```

It returns the following result.

```
[[0,1561535645.599753,0.000141143798828125],[[[3],[["content","LongText"],["_score","Int32"]],["这是我的书 我的书 我的幸福",2],["我的手机忘
带了",1],["幸福的家庭",1]]]]
```

`的` is used 3 times in "这是我的书 我的书 我的幸福", but its score is 2 in this case.
In contrast to `的`, `书` is used 2 times in "这是我的书 我的书 我的幸福" and its score is 2.
This means `书` is regarded as important term than `的` even though frequency is not the same (TF-IDF is used for such a purpose)

**Comment by kou** [comment]
Normally, we should use `pgroonga_full_text_search_condition_with_scorers` to specify scorer: https://pgroonga.github.io/reference/operators/query-v2.html

`pgroonga_command` isn't for normal users.

**Comment by patarapolw** [comment]
@sgon00 So, what was the best?

- zhparser
- pg_jieba
- pgroonga + friso (though I failed to build - https://github.com/kenhys/groonga-tokenizer-friso/issues/6)
- pgroonga + TokenBigram
- pgroonga + TokenTable + Dictionary (I don't even know to do this; but I can easily download CC-CEDICT)

@kou What is the default tokenizer for non-ASCII, anyway?

```sql
SELECT unnest -> 'value' AS "value" FROM unnest(
  pgroonga_tokenize('This is a pen. あきらめないで。你为什么学习普通话？',
                    'tokenizer', 'TokenMecab("include_class", true)',
                    'token_filters', 'TokenFilterNFKC100("unify_kana", true)')
);

SELECT unnest -> 'value' AS "value" FROM unnest(
  pgroonga_tokenize('你为什么学习普通话？',
                    'tokenizer', 'TokenBigram')
);
```

I can ensure that first command is broken for Chinese, but not the second command...

**Comment by kou** [comment]
PGroonga uses `TokenBigram` as the default tokenizer. PGroonga doesn't care ASCII or non-ASCII.

**Comment by patarapolw** [comment]
Actually, CJK might be a little different? It separates by characters, rather than by spaces?

```sql
  SELECT unnest -> 'value' AS "value" FROM unnest(
  pgroonga_tokenize('This is a pen. これはペンです。你为什么学习普通话？',
                    'tokenizer', 'TokenMecab("include_class", true)',
                    'token_filters', 'TokenFilterNFKC100("unify_kana", true)')
  );
```

```js
[
  'this', 'i',   's',
  'a',    'pen', '.',
  'これ', 'は',  'ぺん',
  'です', '。',  '你为',
  '什么', '学',  '习普',
  '通',   '话',  '?'
]
```

```sql
  SELECT unnest -> 'value' AS "value" FROM unnest(
  pgroonga_tokenize('This is a pen. これはペンです。你为什么学习普通话？',
                    'tokenizer', 'TokenBigram')
  );
```

```js
[
  'Th',   'hi',   'is',   's ',   ' i',
  'is',   's ',   ' a',   'a ',   ' p',
  'pe',   'en',   'n.',   '. ',   ' こ',
  'これ', 'れは', 'はペ', 'ペン', 'ンで',
  'です', 'す。', '。你', '你为', '为什',
  '什么', '么学', '学习', '习普', '普通',
  '通话', '话？', '？'
]
```

In any case, `TokenBigram` does quite well for pure Chinese.
