### ISSUE TITLE
multi col and trigger

### ISSUE THREAD

**Issue by kengcher** [pgroonga/pgroonga#110]
Hi
1. Is it possible to build an index on multiple columns e.g.
CREATE INDEX text_idx ON pgroonga.test USING pgroonga (Title, Abstract, Desc);

and how should I query the created index?

2. Do i need to set a trigger when new rows are added? I am using copy to load rather than insert so should I just rerun the create index?

Thank you.

**Comment by kenhys** [comment]
> Is it possible to build an index on multiple columns e.g.

Yes, you can create an index on multiple columns as you mentioned above.

```
CREATE TABLE memos (
  id integer,
  title text,
  content text
);
insert into memos (title,content) values ('groonga', 'groonga sample');
insert into memos (title,content) values ('rroonga', 'rroonga sample');
insert into memos (title,content) values ('mroonga', 'mroonga sample');
CREATE INDEX index ON memos USING pgroonga (title, content);
```

> Do i need to set a trigger when new rows are added? I am using copy to load rather than insert so should I just rerun the create index?

No, created indexes are updated automatically when new rows are added. no need to set a trigger. If you changed schema and want new column  against already created index on multiple columns, you need to re create it.

**Comment by askdkc** [comment]
@devhandler 

That's more like PostgreSQL index example rather than PGroonga only.

And if you create multiple indexes, you need to be careful about querying order. If you create index like above `(title, content)`, you need to query title first then content second in order to use index efficiently. Otherwise you don't get that performance boost😢

If you create indexes for each column like this

```sql
CREATE INDEX title_index ON memos USING pgroonga (title);

CREATE INDEX content_index ON memos USING pgroonga (content);
```

Then you don’t need to worry about the querying order and PGroonga can still automatically use these indexes according to its needs.😏

But this tip is not only for PostgreSQL but for many other SQL indexes. If you're using RDB, this index knowledge saves you a ton of time😉

**Comment by askdkc** [comment]
@devhandler 

This example might be helpful 

https://stackoverflow.com/questions/19367288/multi-column-index-order-and-in-queries

If you add columns to your table, like col1, col2, then just create index for each columns

```sql
CREATE INDEX col1_idx ON col1 USING pgroonga;

CREATE INDEX col2_idx ON col2 USING pgroonga;
```

This should be usually all you need.
