### ISSUE TITLE
full word search

### ISSUE THREAD

**Issue by kengcher** [pgroonga/pgroonga#118]
Hi 

If i would like to find "CAT" instead of words that have the substring "CAT" e.g. "CATS", is there a way to do it in pgroonga since spaces are automatically excluded if i use " CAT ".

Thank you.

**Comment by komainu8** [comment]
We use `TokenDelimit` as tokenizer and `hash_table` as lexicon type to find "CAT" instead of words that have the substring "CAT".

Example:

```sql
CREATE EXTENSION pgroonga;
SET enable_seqscan = off;

CREATE TABLE memos (
id integer,
content text
);

CREATE INDEX pgroonga_content_index
ON memos
USING pgroonga (content)
WITH (lexicon_type='hash_table', tokenizer='TokenDelimit');

INSERT INTO memos VALUES (1, 'They are cats');
INSERT INTO memos VALUES (2, 'She is a cat');

SELECT * FROM memos WHERE content &@ 'cat';
 id |   content    
----+--------------
  2 | She is a cat
(1 row)

c=# DELETE from memos WHERE id=2;
DELETE 1
c=# SELECT * FROM memos ;
 id |    content    
----+---------------
  1 | They are cats
(1 row)

c=# SELECT * FROM memos WHERE content &@ 'cat';
 id | content 
----+---------
(0 rows)
```

`TokenDelimit` extracts token by splitting one or more space characters (U+0020).
Therefore "They are cats" is tokenized to `They`, `are`, and `cats`.

If we search `cat`, "They are cats" isn't hit.
However, PGroonga executes prefix search when the search result is 0 in default.
Therefore "They are cats" is hit when the result of a search by `cat` is 0.

`hash_table` doesn't support prefix search.
Therefore if we use `hash_table` for lexicon type, "They are cats" isn't hit even the result of a search by `cat` is 0.

**Comment by kengcher** [comment]
Can you create both default pgroonga (content) without and with (lexicon_type='hash_table', tokenizer='TokenDelimit') at the same time with different index names and select which one to use?

**Comment by komainu8** [comment]
Could you show your use case with sample data?

**Comment by kou** [comment]
No response.
