### ISSUE TITLE
libgroonga-dev for arm64

### ISSUE THREAD

**Issue by DeoLeung** [pgroonga/pgroonga#174]
Hi, is there possible to release a `libgroonga-dev` for arm64, I don't see it on http://packages.groonga.org/debian/dists/buster/main/

currently I have to build it from source using below
```
FROM postgres:12
ADD https://packages.groonga.org/debian/groonga-archive-keyring-latest-buster.deb /tmp/groonga-archive-keyring-latest-buster.deb
ENV INSTALL='apt-get install -y --no-install-recommends'

RUN  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free\
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free\
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free\
deb http://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free" > /etc/apt/sources.list && \
    localedef -f UTF-8 -i zh_CN zh_CN.UTF-8 && \
    apt-get update && \
    ${INSTALL} libgroonga-dev libmsgpack-dev
ADD https://packages.groonga.org/source/pgroonga/pgroonga-2.2.8.tar.gz /tmp/pgroonga-2.2.8.tar.gz
RUN ${INSTALL} build-essential postgresql-server-dev-12 && \
    cd /tmp/ && \
    tar xzvf pgroonga-2.2.8.tar.gz && \
    cd pgroonga-2.2.8 && \
    make HAVE_MSGPACK=1 && \
    make install
```

it was built successfully but encountered #142 again
using os
`openEuler 20.03 64bit with ARM`

**Comment by komainu8** [comment]
We don't provide `libgroonga-dev` for arm64 on `packages.groonga.org`.
Because we don't have a build environment for arm64.

The official Debian GNU/Linux Buster APT repository provides `libgroonga-dev` for arm64.
However, `libgroonga-dev` is old in the official Debian GNU/Linux Buster APT repository.

Probably, if we use Debian GNU/Linux Bullseye APT repository as below, we get the latest `libgroonga-dev`.

1. We set to `/etc/apt/preferences` as below.

```
% cat /etc/apt/preferences
Package: *
Pin: release a=stable
Pin-Priority: 900

Package: *
Pin: release a=testing
Pin-Priority: 99
```

2. We execute the following command

```
% echo "deb http://deb.debian.org/debian testing main" > /etc/apt/sources.list
```

3. We install libgroonga-dev as below.

```
% apt install libgroonga-dev/testing
```

**Comment by kou** [comment]
We can build `libgroonga-dev` for arm64 by adding https://github.com/groonga/groonga/blob/master/packages/apt/debian-buster-arm64/from with `arm64v8/debian:buster` (we also need `qemu-user-static` on host when we use the image on amd64) like https://github.com/groonga/groonga/blob/master/packages/apt/debian-buster-i386/from .

I think that arm64 support is more important than i386 support. Because i386 environments will be decreased but arm64 environments will be increased.

**Comment by DeoLeung** [comment]
looking forward to the arm build!

currently I tried installing from `testing`, but it removes `postgresql-server-dev-12` which causes the `pgroonga` build fails to find `postgres.h`

**Comment by komainu8** [comment]
Hmmm...

We decided to build `libgroonga-dev` for arm64.
We can probably provide it in the next release on 2021/3/29.

Could you build PGroonga with `libgroonga-dev` for arm64 that schedules for release on 2021/3/29 to packages.groonga.org without using `libgroonga-dev` of the `testing` repository?

**Comment by DeoLeung** [comment]
sure, looking forward to the release

**Comment by komainu8** [comment]
`libgroonga-dev` for arm64 on Debian buster has been released.
Could you try it?

**Comment by DeoLeung** [comment]
> `libgroonga-dev` for arm64 on Debian buster has been released.
> Could you try it?

we tried it today, the database image build succeeded and some of our test pipelines already passed

Thank you very much for the help!

**Comment by kou** [comment]
Thanks for confirming it.

BTW, we also provide `postgresql-12-pgdg-pgroonga` for arm64.
