### ISSUE TITLE
pgroonga_highlight_html with index highlights start of text

### ISSUE THREAD

**Issue by lilydjwg** [pgroonga/pgroonga#192]
With this index,

```sql
CREATE INDEX message_idx ON messages USING pgroonga (text) WITH (tokenizer='TokenBigramIgnoreBlank');
```

The highlight is always at start:
```
=> select pgroonga_highlight_html('some text for test', pgroonga_query_extract_keywords('test'), 'message_idx');
             pgroonga_highlight_html             
-------------------------------------------------
 <span class="keyword"></span>some text for test
```

**Comment by komainu8** [comment]
If we want use `pgroonga_highlight_html()` with index, we need to use `TokenNgram` with `report_source_location` option in `tokenizer` as below. (ref: https://pgroonga.github.io/reference/functions/pgroonga-highlight-html.html)

```sql
CREATE INDEX message_idx ON messages USING pgroonga (text) WITH (tokenizer='TokenNgram("report_source_location", true)');
```

However, I think that we don't need to specify the index in `pgroonga_highlight_html()` in your example.
Because we don't change normalizer from default in your example.

Therefore, the following query is enough in this example.

```sql
select pgroonga_highlight_html('some text for test', pgroonga_query_extract_keywords('test'));
             pgroonga_highlight_html             
-------------------------------------------------
 some text for <span class="keyword">test</span>
```
