### ISSUE TITLE
PostgreSQL 9.6 WAL interface

### ISSUE THREAD

**Issue by patrick-jones** [pgroonga/pgroonga#25]
PostgreSQL 9.6 has just been released. Would the new [generic WAL interface](http://paquier.xyz/postgresql-2/postgres-9-6-feature-highlight-generic-wal-interface/) in 9.6 allow pgroonga to support streaming replication?

**Comment by jmealo** [comment]
This would be huge. Can someone see what this would take to implement?

**Comment by kou** [comment]
I've implemented generic WAL support.
It's included PGroonga as an experimental feature since PGroonga 1.1.6.

I'm writing document about it. I'll announce it after I've written it.

Anyway, could you test the feature and report your test result?

Here are instructions to use the feature:

  1. Install (or upgrade to) PostgreSQL 9.6 on both master and slaves.

  2. [Install](http://pgroonga.github.io/install/) (or [upgrade](http://pgroonga.github.io/upgrade/) to) the latest PGroonga. on both master and slaves 

  3. Change `postgresql.conf` on only master like the followings:

     1. Change `wal_level` to `replica` or `logical` (normal configuration for streaming replication):

            wal_level = replica

     2. Increase `max_wal_senders` like the following (normal configuration for streaming replication):

            max_wal_senders = 5

     3. Change `pgroonga.enable_wal` to `on`:

            pgroonga.enable_wal = on

  4. Add an user for replication to `pg_hba.conf` on only master like the following (normal configuration for streaming replication):

         local   replication     replica                                trust
         host    replication     replica        127.0.0.1/32            trust
         host    replication     replica        ::1/128                 trust

  5. Run PostgreSQL on master.

  6. Create PGroonga indexes on master.

  7. Run `SELECT pgroonga.command('io_flush');` and stop updating on master until the below `pg_basebackup` on slaves is finished.

  8. Run `pg_basebackup -h master.example.com -D DB_PATH --xlog --progress -U replica -R` on slaves.

  9. Change `postgresql.conf` on only slaves like the followings:

     1. Change `hot_standby` to `on` (normal configuration for streaming replication):

            hot_standby = on

  10. Start PostgreSQL on slaves.

See also:

  * [`pgroonga.enable_wal`](http://pgroonga.github.io/reference/parameters/enable_wal.html)

**Comment by patrick-jones** [comment]
Very exciting news! I'll try it out this week.

**Comment by kou** [comment]
Thanks.
http://pgroonga.github.io/reference/replication.html will help you.

**Comment by kou** [comment]
If you find any problems for replication, please open a new issue.
