### ISSUE TITLE
Weird similar search behavior

### ISSUE THREAD

**Issue by ghevge** [pgroonga/pgroonga#392]
### What happened?

I have a query that looks like this:

`select * from labels where value &@* 'f' and locale = 'en';`

which returns 93 records.

If I change the searched text to 'fr', the result will be empty.

If I change more the searched text to 'fre', the result set will contain 23 records. 

My question is: why the second query  in which I'm searching for  'fr' is returning an empty set, when obviously it should return something in between 93 and 23 records?

Thanks

Table schema is:

```
CREATE TABLE public.labels (
	id uuid NOT NULL,
	value varchar(300) NOT NULL,
	locale varchar(30) NOT NULL,
	username varchar(255) NOT NULL,
	creation_time timestamp NOT NULL,
	update_time timestamp NOT NULL,
	"key" varchar(100) NOT NULL DEFAULT NULL::character varying,
	commit_id uuid NULL,
	CONSTRAINT labels_pkey PRIMARY KEY (id),
	CONSTRAINT labels_unique_key UNIQUE (key),
	CONSTRAINT labels_value_locale_key UNIQUE (value, locale)
);
CREATE INDEX label_value_idx ON public.labels USING pgroonga (value pgroonga_varchar_full_text_search_ops_v2);
CREATE INDEX labels_id_idx ON public.labels USING btree (id);
CREATE INDEX labels_locale_idx ON public.labels USING btree (locale); 
```

Let me know if you need the 93 records returned by the first query. I can provide them to you.

### How to reproduce it

check above

### Expected behavior

A non empty set must be returned

### Environment

groonga/pgroonga:3.1.5-debian-16

**Comment by ghevge** [comment]
BTW, the query `select * from labels where value ilike '%fr%' and locale = 'en'; ` returns 38 records. So I would expect similar text search to return something on the same range.

**Comment by kou** [comment]
Yes, please.

**Comment by ghevge** [comment]
Please find attached the data.  
[data.txt](https://github.com/pgroonga/pgroonga/files/13860699/data.txt)

**Comment by kou** [comment]
Thanks.
But I couldn't reproduce this. I got 33 records with `fr`.

**Comment by ghevge** [comment]
hmm... what could be wrong on my side then ?

**Comment by ghevge** [comment]
I've tried the same query on a different DB which has much more records, and I still see this weird behavior. But it behaves slightly different.
eg: querying for 'f' returns 20 rows
'fr' returns 171 rows
'fre' returns 1 row
'free' returns 347 rows

**Comment by kou** [comment]
I could reproduce this with new data.

It's caused by the "match escalation" (auto loose search) feature.
There is no record that has `f`/`fre` token but there are some records that have `fr` token.
If there is one or more records exist, the "match escalation" feature isn't used. So `fr` (no "match escalation") is 0 hit.

If you want to always use the "match escalation" feature, you can use `set pgroonga.force_match_esclation = on;`: https://pgroonga.github.io/reference/parameters/force-match-escalation.html

**Comment by ghevge** [comment]
@kou thanks! It works now after setting  `pgroonga.force_match_esclation = on;` 

question: shouldn't this flag be set to on by default in pgroonga based on this behavior ?

**Comment by kou** [comment]
No. It may increase false-positive match records.

**Comment by ghevge** [comment]
> No. It may increase false-positive match records.
But at the same time it excludes a lot more valid records.

**Comment by kou** [comment]
They are not valid records.
The default tokenizer tokenizes alphabet based texts as words. For example, "free food" is tokenized as "free" and "food". It should not be matched by "fr" because there is no "fr" token in the record.
If you like all substring tokenization, you may want to use `CREATE INDEX label_value_idx ON public.labels USING pgroonga (value pgroonga_varchar_full_text_search_ops_v2) WITH (tokenizer = 'TokenNgram("unify_alphabet", false, "unify_symbol", false, "unify_digit", false)');`. In general, it will return noisy results.
