### ISSUE TITLE
Two queries for the same string return different results

### ISSUE THREAD

**Issue by SnowySailor** [pgroonga/pgroonga#421]
### What happened?

I have two queries that are being run on a database that contains text from various manga. The indexed column is called `fulltext` and it contains the text of an entire page without spaces.

When I run this query:
```sql
select id, fulltext from "Page" where fulltext &@ '葬送のフリーレン' and id = 3003;
```
I get back 1 result (as expected)
![image](https://github.com/pgroonga/pgroonga/assets/6320753/247dbfcb-a22d-4ffe-9001-cc1a10231513)

However, when I remove the `and id = 3003` from the `where` clause, I get 5 results, however none of the results are from page 3003 (which has a match, as seen above). I only get back 3311, 3113, 3111, 3116, and 3321.
```sql
select id, fulltext from "Page" where fulltext &@ '葬送のフリーレン'
```
![image](https://github.com/pgroonga/pgroonga/assets/6320753/efae8f21-bd61-4749-b642-4b41229d7648)

### How to reproduce it

I have created my index as such:
```sql
CREATE INDEX pgroonga_blocks_index ON public."Page" USING pgroonga (fulltext) WITH (tokenizer='TokenMecab')
```
And when I run the two queries that I mentioned before, one of them returns a result for a page (3003), however the other (a more broad query) returns a list of results that does _not_ include page 3003 (it only contains 3311, 3113, 3111, 3116, and 3321).

### Expected behavior

Query returns matching results when there are relevant matches

### Environment

I am using the `groonga/pgroonga:latest-debian-16` docker image
- OS: Debian
- OS Version: Debian GNU/Linux 12 (bookworm)
- PostgreSQL Version: 16.1
- PGroonga Version: 3.1.5
- libgroonga Version: 13.1.1

**Comment by SnowySailor** [comment]
I have also tried creating the index with
```sql
CREATE INDEX pgroonga_blocks_index ON public."Page" USING pgroonga (fulltext) WITH (tokenizer='')
```
and my results are different, but still similar. Without the index, I get 42 results and with the index I get 3.

**Comment by kou** [comment]
葬送のフリーレン！

Could you try `SET pgroonga.force_match_escalation = on;`?
See also: https://pgroonga.github.io/reference/parameters/force-match-escalation.html

Could you also try `CREATE INDEX pgroonga_blocks_index ON public."Page" USING pgroonga (fulltext)` that uses `TokenBigram` instead of `TokenMecab`?

**Comment by SnowySailor** [comment]
I've started reading it to pick up new vocabulary after watching the anime. For context, I'm currently trying to improve the search that we implemented [here](https://github.com/m-wynn/next-mokuro-bookshelf) because it currently only searches within a single vertical line of text and not an entire speech bubble. After merging all the page text together I started noticing that the results that were coming back were a little inconsistent.

I tried using `SET pgroonga.force_match_escalation = on;` but that didn't seem to help. However, when I use `TokenBigram` then it starts returning the same numbers as a normal table scan (without an index)! All those queries are running in <5ms very consistently too, which is great (much better than no index at all). I think Bigram is the solution here. Do you know why Bigram works better than Mecab in this situation? For reference, here is my (new) index definition:
```sql
CREATE INDEX pgroonga_blocks_index ON public."Page" USING pgroonga ("blockText") WITH (tokenizer='TokenBigram');
```
And `blockText` is a `text[]` field, containing each block of text as an array entry. Here is a sample:
![image](https://github.com/pgroonga/pgroonga/assets/6320753/de7b920b-43b5-4b4b-b23f-5f9702e1c800)

Thank you for your help!

**Comment by kou** [comment]
> Do you know why Bigram works better than Mecab in this situation?

`TokenMecab` tokenizes a given text with context. `葬送のフリーレン` may be tokenized to `[葬送, の, フリーレン]`, `[葬送, の, フ, リー, レン]` or something based on texts around it.

`TokenBigram` tokenizes a given text without context. So `葬送のフリーレン` is always tokenized to `[葬送, 送の, のフ, フリ, フリ, リー, ーレ, レン, ン]`.

Both of indexed text and query text are tokenized. If they are different, the indexed text isn't matched. `SET pgroonga.force_match_escalation = on;` relaxes it but it'll not perfect for all cases.
See also: https://groonga.org/docs/troubleshooting/different_results_with_the_same_keyword.html

> For reference, here is my (new) index definition:
> 
> ```sql
> CREATE INDEX pgroonga_blocks_index ON public."Page" USING pgroonga ("blockText") WITH (tokenizer='TokenBigram');
> ```

You can omit `WITH (...)` because `TokenBigram` is the default.

**Comment by SnowySailor** [comment]
Oh I see. That makes sense. Thanks for that link, that was helpful 🙏
