### ISSUE TITLE
Crash when specifying `pgroonga.log_type = file` on Windows

### ISSUE THREAD

**Issue by efendioglukdz** [pgroonga/pgroonga#539]
### What happened?

Hello friends,

I have a PostgreSQL DB 16.4.1 and PGRoonga 3.2.2 installed.
When I put following line in postgresql.conf:
`pgroonga.log_type = file`

And I try to create my extension like follwing:
`TestDB=# CREATE EXTENSION pgroonga;
server closed the connection unexpectedly
        This probably means the server terminated
abnormally
        before or while processing the request.
The connection to the server was lost. Attempting
reset: Failed.
The connection to the server was lost. Attempting
reset: Failed.
!?>`

I get that error. If I disable the line:
`#pgroonga.log_type = file`

everything works fine.

### How to reproduce it

Activate `pgroonga.log_type = file` in postgresql.conf

### Expected behavior

`server closed the connection unexpectedly
        This probably means the server terminated
abnormally
        before or while processing the request.
The connection to the server was lost. Attempting
reset: Failed.
The connection to the server was lost. Attempting
reset: Failed.`

### Environment

- OS: [Windows Server 2022 Standard 21H2 ]
- PostgreSQL Version: [e.g. 16.4.1]
- PGroonga Version: [e.g. 3.2.2]

**Comment by efendioglukdz** [comment]
Did I miss something here? The pgroonga.log is written anyway without the mentioned setting in postgresql.conf.
Is that setting meanwhile deprecated? There is no document for 3.x.x versions, as far as I can see.

**Comment by abetomo** [comment]
The default value of `pgroonga.log_type` is `file`, so it is written to the log without setting `pgroonga.log_type = file`.
I opened a PR to add default values since there was no description of them.
https://github.com/pgroonga/pgroonga.github.io/pull/378

Also, the error with `pgroonga.log_type` has been fixed and will be fixed in the next release, 3.2.3.

**Comment by kou** [comment]
Ah, the current documents are for 2.X and 3.X.
I've fixed the text: https://github.com/pgroonga/pgroonga.github.io/commit/3d76b8672702da385948b267b77d185978202e8a

The crash was fixed by https://github.com/groonga/groonga/pull/1871 as @abetomo mentioned.
The Windows binaries of the next version will include the fix.

Workaround: Don't specify it because it's the default value.

**Comment by kou** [comment]
Ah, sorry. #535 is the fix of this.
